### PR TITLE
Split kube-vip template to its own template.

### PR DESCRIPTION
**Pull request by cprivite**
Split kube-vip template to its own template.

### CODE REVIEW

**Comment by cprivite** [comment]
Do you mind if we just merge this in to your branch for now and continue to follow up in [your PR](https://github.com/detiber/cluster-api-provider-packet/pull/65) about the readme and the EIP handling? I'll likely end up submitting separate PRs to your branch to address each of those.

**Comment by DavidSpek** [comment]
@cprivite sure that's fine by me

**Comment by DavidSpek** [comment]
Is this ready for merging?

**Comment by cprivite** [comment]
Yes, please.

**Pull request merged**
